version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:cf:9a:cd:d4:3e:4e:fc:de:99:88:5c:fa:96:98:f6"
      - run:
          name: Deploy to AWS
          command: |
            ssh ec2-user@52.32.105.241 \
              "cd /home/ec2-user/batch-organizer/batch_organizer; \
              git pull; \
              rm -rf node_modules; \
              sudo fuser -k 3000/tcp; \
              yarn; \
              yarn build; \
              nohup yarn serve &;"

workflows:
  test-and-deploy:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - deploy:
          requires:
            - node/test
