version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy to AWS
          command: |
            ssh -i ec2-user@52.32.105.241; \
              cd /home/ec2-user/batch-organizer/batch_organizer; \
              git pull; \
              rm -rf node_modules; \
              yarn build; \
              yarn serve; \

workflows:
  test:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
  deploy:
    jobs:
      - deploy
